#!/usr/bin/env python3
"""SIM Hub guided, repeatable Linux deployment without third-party Python packages.

The script never changes DNS provider records or prints credential values to logs.
Existing .env / Caddyfile are not overwritten unless explicitly upgraded from a
compatible managed installation. External reverse proxy is supported.
"""
from __future__ import annotations

import argparse
import ipaddress
import os
from pathlib import Path
import re
import secrets
import shutil
import socket
import subprocess
import sys
import urllib.request
import base64

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / ".env"
CADDY = ROOT / "Caddyfile"
DOMAIN = re.compile(r"^(?=.{1,253}$)(?!-)[a-z0-9-]+(?:\.[a-z0-9-]+)+$", re.I)


def run(*argv: str, check: bool = True, capture: bool = False):
    return subprocess.run(argv, cwd=ROOT, check=check, text=True,
                          stdout=subprocess.PIPE if capture else None,
                          stderr=subprocess.PIPE if capture else None)


def ask(label: str, default: str = "") -> str:
    value = input(f"{label}{' [' + default + ']' if default else ''}: ").strip()
    return value or default


def validate_domain(value: str) -> str:
    value = value.strip().lower().rstrip(".")
    if not DOMAIN.fullmatch(value) or any(len(label) > 63 for label in value.split(".")):
        raise ValueError("Expected an FQDN (e.g. admin.example.com) without protocol or path")
    return value


def dns_addresses(domain: str) -> set[str]:
    try:
        return {entry[4][0] for entry in socket.getaddrinfo(domain, None, type=socket.SOCK_STREAM)}
    except socket.gaierror:
        return set()


def public_ipv4() -> str | None:
    try:
        with urllib.request.urlopen("https://api.ipify.org", timeout=5) as response:
            value = response.read(128).decode().strip()
        addr = ipaddress.ip_address(value)
        return value if addr.version == 4 and addr.is_global else None
    except (OSError, ValueError):
        return None


def ensure_ports() -> None:
    for port in (80, 443):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                sock.bind(("0.0.0.0", port))
            except OSError as exc:
                raise RuntimeError(f"Port {port} not available; stop existing reverse proxy or use --mode external") from exc


def check_docker() -> None:
    if not shutil.which("docker"):
        raise RuntimeError("Docker Engine missing. Install Docker Engine and Compose plugin first.")
    for args in (("docker", "info", "--format", "{{.ServerVersion}}"),
                 ("docker", "compose", "version")):
        result = run(*args, check=False, capture=True)
        if result.returncode:
            raise RuntimeError(f"Command failed: {' '.join(args)}: {result.stderr.strip()}")


def caddy_config(admin: str, node: str) -> str:
    security = ('    header {\n'
                '        Strict-Transport-Security "max-age=31536000"\n'
                '        X-Content-Type-Options nosniff\n'
                '        X-Frame-Options DENY\n'
                '        Referrer-Policy no-referrer\n'
                '    }\n')
    return (f"# Generated by SIM Hub setup; keep the node and admin origins separate.\n"
            f"{admin} {{\n    @internal_health path /healthz /readyz\n    respond @internal_health 404\n    encode zstd gzip\n"
            f"    reverse_proxy 127.0.0.1:8787 {{\n        header_up X-Forwarded-For {{remote_host}}\n    }}\n"
            f"{security}}}\n\n"
            f"{node} {{\n    @internal_health path /healthz /readyz\n    respond @internal_health 404\n    encode zstd gzip\n"
            f"    reverse_proxy 127.0.0.1:8787 {{\n        header_up X-Forwarded-For {{remote_host}}\n    }}\n"
            f"{security}}}\n")


def parse_env(content: str) -> dict[str, str]:
    values = {}
    for line in content.splitlines():
        if line.strip() and not line.lstrip().startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip()
    return values


def set_vars(template: str, values: dict[str, str]) -> str:
    lines = template.splitlines()
    seen = set()
    out = []
    for line in lines:
        key = line.split("=", 1)[0].strip()
        if key in values and "=" in line and not line.lstrip().startswith("#"):
            out.append(key + "=" + values[key])
            seen.add(key)
        else:
            out.append(line)
    for key, value in values.items():
        if key not in seen:
            out.append(key + "=" + value)
    return "\n".join(out) + "\n"


def secure_create(path: Path, contents: str) -> None:
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(contents)
    except BaseException:
        path.unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description="SIM Hub guided first-time deployment and upgrades")
    parser.add_argument("--admin-domain", help="Browser management HTTPS FQDN")
    parser.add_argument("--node-domain", help="Android / modem HTTPS FQDN")
    parser.add_argument("--username", default="admin", help="Browser admin display/login name")
    parser.add_argument("--mode", choices=("managed", "external"), default="managed")
    parser.add_argument("--skip-dns-check", action="store_true", help="For provisioning before DNS propagates")
    parser.add_argument("--no-start", action="store_true", help="Generate configuration but do not start Docker")
    parser.add_argument("--upgrade", action="store_true", help="Reuse an existing deployment unchanged")
    args = parser.parse_args()

    print("\nSIM Hub deployment — Linux + Docker\n")
    if sys.platform != "linux":
        raise RuntimeError("This installer targets Linux. Configure macOS/Windows with the documented Compose path.")
    check_docker()
    print("[ok] Docker Engine and Docker Compose available")
    existing = parse_env(ENV.read_text(encoding="utf-8")) if ENV.exists() else {}
    if ENV.exists() and not args.upgrade:
        raise RuntimeError(".env already exists. Use --upgrade to preserve configuration and restart, not overwrite it.")

    admin = validate_domain(args.admin_domain or existing.get("SIMHUB_MANAGEMENT_ORIGIN", "").removeprefix("https://") or ask("Management domain"))
    node = validate_domain(args.node_domain or existing.get("SIMHUB_PUBLIC_BASE_URL", "").removeprefix("https://") or ask("Device domain"))
    if admin == node:
        raise RuntimeError("Management and device FQDNs must be different")
    user = args.username.strip()
    if not re.fullmatch(r"[A-Za-z0-9_.-]{2,64}", user):
        raise RuntimeError("Username must have 2-64 characters (letters, numbers, _.-)")
    if existing and (existing.get("SIMHUB_MANAGEMENT_ORIGIN") != "https://" + admin or
                     existing.get("SIMHUB_PUBLIC_BASE_URL") != "https://" + node):
        raise RuntimeError("An upgrade cannot silently change domain/Passkey RP ID. Migrate explicitly.")

    pub = public_ipv4()
    for domain in (admin, node):
        records = dns_addresses(domain)
        print(f"[DNS] {domain} -> {', '.join(sorted(records)) or '(unresolved)'}")
        if not args.skip_dns_check and (not records or (pub and pub not in records)):
            raise RuntimeError(f"DNS for {domain} does not resolve to this server's public IPv4"
                               + (f" ({pub})" if pub else "") + "; set A record and retry.")
    if not pub:
        print("[warn] Cannot verify public IPv4; check A/AAAA manually before TLS issuance.")
    if not existing and args.mode == "managed":
        ensure_ports()
        print("[ok] HTTP/HTTPS ports available")
    if existing and args.mode == "managed" and not CADDY.exists():
        raise RuntimeError("Managed upgrade requested but Caddyfile is missing")
    if not existing:
        token = secrets.token_urlsafe(48)
        totp = base64.b32encode(secrets.token_bytes(20)).decode().rstrip("=")
        tpl = (ROOT / ".env.example").read_text(encoding="utf-8")
        vals = {"SIMHUB_ADMIN_TOKEN": token,
                "SIMHUB_TOTP_SECRET": totp, "SIMHUB_REQUIRE_TOTP": "true",
                "SIMHUB_ADMIN_USERNAME": user,
                "SIMHUB_PUBLIC_BASE_URL": "https://" + node,
                "SIMHUB_MANAGEMENT_ORIGIN": "https://" + admin,
                "SIMHUB_SEPARATE_SURFACES": "true"}
        secure_create(ENV, set_vars(tpl, vals))
        print("[ok] Created .env with owner-only permissions (0600).")
        print("[security] TOTP and emergency admin token are in .env. Back up securely, do not publish.")
        if args.mode == "managed":
            secure_create(CADDY, caddy_config(admin, node))
            print("[ok] Caddyfile created (managed TLS + reverse proxy).")
    else:
        print("[ok] Existing .env preserved.")
    if args.mode == "external":
        print("\n[proxy] Configure your existing reverse proxy to 127.0.0.1:8787")
        print(f"        Management: https://{admin} | Node: https://{node}")
        print("        Overwrite X-Forwarded-For with authenticated client IP; never expose port 8787.")
    if not args.no_start:
        files = ["-f", "docker-compose.yml"]
        if args.mode == "managed":
            files += ["-f", "compose.caddy.yml"]
        run("docker", "compose", *files, "up", "-d", "--build")
        result = run("docker", "compose", *files, "ps", capture=True)
        print(result.stdout)
        print("Check internal readiness: docker compose exec -T simhub python3 -c \"import urllib.request; print(urllib.request.urlopen('http://127.0.0.1:8787/readyz').read().decode())\"")
    print(f"\nManagement: https://{admin}\nDevice endpoint: https://{node}")
    print("After HTTPS works, sign in, create/import a local Vault, enroll the first node, register a Passkey.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        raise SystemExit(1)
