const $ = (id) => document.getElementById(id);
const enc = new TextEncoder();
const dec = new TextDecoder();
const VAULT_STORE = 'simhub_vault_v1';
const PBKDF2_ITER = 310000;
const AUTO_LOCK_MS = 15 * 60 * 1000;

let vaultKey=null,vaultRaw=null,devices=[],events=[],decryptedEvents=[],lastSeq=0,pollTimer=null,eventSource=null,autoLockTimer=null,refreshTimer=null,lastActivity=Date.now();
const deviceKeyCache=new Map();
const titles={inbox:['Inbox','End-to-end encrypted SMS'],send:['Send SMS','Encrypted remote sending'],devices:['Devices','SIM nodes and live state'],settings:['Settings','Enrollment, vault and notifications']};

function b64u(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');s+='='.repeat((4-(s.length%4))%4);const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function field(v){return b64u(enc.encode(String(v==null?'':v)));}
function eventAad(deviceId,eventId,kind,occurredAt,subscriptionId,hasOtp){return 'simhub-event-v2|'+field(deviceId)+'|'+field(eventId)+'|'+field(kind)+'|'+occurredAt+'|'+field(subscriptionId)+'|'+(hasOtp?'1':'0');}
function commandAad(deviceId,commandId,type,createdAt,expiresAt,idempotencyKey){return 'simhub-command-v2|'+field(deviceId)+'|'+field(commandId)+'|'+field(type)+'|'+createdAt+'|'+expiresAt+'|'+field(idempotencyKey);}
function uuid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+b64u(crypto.getRandomValues(new Uint8Array(12)));}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600);}
function fmtTime(ts){if(!ts)return '—';return new Intl.DateTimeFormat(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(ts*1000));}
function deviceName(id){const d=devices.find(x=>x.id===id);return d?d.name:'SIM Node';}

async function deriveWrapKey(passphrase,salt){const base=await crypto.subtle.importKey('raw',enc.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt,iterations:PBKDF2_ITER,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function wrapVaultRaw(raw,passphrase){if(passphrase.length<10)throw new Error('Use a vault passphrase of at least 10 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),wrapKey=await deriveWrapKey(passphrase,salt);const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:iv,additionalData:enc.encode('simhub-vault-wrap-v1')},wrapKey,raw));localStorage.setItem(VAULT_STORE,JSON.stringify({v:1,kdf:'PBKDF2-SHA256',iterations:PBKDF2_ITER,salt:b64u(salt),iv:b64u(iv),ct:b64u(ct)}));}
async function importVault(raw){vaultRaw=new Uint8Array(raw);vaultKey=await crypto.subtle.importKey('raw',vaultRaw,{name:'AES-GCM'},false,['encrypt','decrypt']);deviceKeyCache.clear();resetAutoLock();}
async function createVault(passphrase){const raw=crypto.getRandomValues(new Uint8Array(32));await wrapVaultRaw(raw,passphrase);await importVault(raw);}
async function importRecoveryFlow(){const text=$('recoveryKey').value.trim(),prefix='SIMHUB-RECOVERY-V1:';if(!text.startsWith(prefix))throw new Error('Recovery key format is invalid.');const raw=unb64u(text.slice(prefix.length));if(raw.length!==32)throw new Error('Recovery key length is invalid.');await wrapVaultRaw(raw,$('passphrase').value);await importVault(raw);$('recoveryKey').value='';toast('Recovery key imported and wrapped locally');}
async function unlockVault(passphrase){const obj=JSON.parse(localStorage.getItem(VAULT_STORE)||'null');if(!obj||!obj.ct)throw new Error('No vault exists in this browser. Create or import one first.');const wrapKey=await deriveWrapKey(passphrase,unb64u(obj.salt));try{const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(obj.iv),additionalData:enc.encode('simhub-vault-wrap-v1')},wrapKey,unb64u(obj.ct));await importVault(raw);}catch(e){throw new Error('Vault passphrase is incorrect or the local vault is damaged.');}}
async function keyIdForRaw(raw){const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',raw));return b64u(digest.slice(0,12));}
async function deriveLegacyDevice(deviceId){if(!vaultRaw)throw new Error('Vault locked');const ikm=await crypto.subtle.importKey('raw',vaultRaw,'HKDF',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt:enc.encode('simhub-device-v1'),info:enc.encode(deviceId)},ikm,256);const raw=new Uint8Array(bits),key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);return {raw:raw,key:key,kid:await keyIdForRaw(raw),mode:'legacy'};}
async function wrapNodeKey(raw,kid){const iv=crypto.getRandomValues(new Uint8Array(12)),aad=enc.encode('simhub-node-key-wrap-v1|'+kid),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:iv,additionalData:aad},vaultKey,raw));return {v:1,alg:'A256GCM',iv:b64u(iv),ct:b64u(ct)};}
async function unwrapNodeKey(envelope,kid){const raw=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(envelope.iv),additionalData:enc.encode('simhub-node-key-wrap-v1|'+kid)},vaultKey,unb64u(envelope.ct)));if(await keyIdForRaw(raw)!==kid)throw new Error('Wrapped node key does not match key id');return raw;}
async function deviceCrypto(deviceId){if(deviceKeyCache.has(deviceId))return deviceKeyCache.get(deviceId);const info=devices.find(x=>x.id===deviceId);let out;if(info&&info.keyId&&info.wrappedKey){const raw=await unwrapNodeKey(info.wrappedKey,info.keyId),key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);out={raw:raw,key:key,kid:info.keyId,mode:'node'};}else out=await deriveLegacyDevice(deviceId);deviceKeyCache.set(deviceId,out);return out;}
async function decryptEvent(e){const cipher=e.ciphertext;if(cipher&&cipher.v===1){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(cipher.iv),additionalData:enc.encode('simhub-event-v1')},vaultKey,unb64u(cipher.ct));return JSON.parse(dec.decode(pt));}if(!cipher||cipher.v!==2)throw new Error('Unsupported ciphertext version');let d=await deviceCrypto(e.deviceId);if(cipher.kid!==d.kid){const legacy=await deriveLegacyDevice(e.deviceId);if(cipher.kid!==legacy.kid)throw new Error('Node key mismatch');d=legacy;}const aad=eventAad(e.deviceId,e.eventId,e.kind,e.occurredAt,e.subscriptionId,e.hasOtp),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(cipher.iv),additionalData:enc.encode(aad)},d.key,unb64u(cipher.ct));return JSON.parse(dec.decode(pt));}
function versionAtLeast(v,target){const a=String(v||'0').split('.').map(Number),b=String(target).split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y;}return true;}
async function encryptCommand(deviceId,outer,payload){const info=devices.find(x=>x.id===deviceId);if(!versionAtLeast(info&&info.appVersion,'0.1.5')){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:iv,additionalData:enc.encode('simhub-command-v1')},vaultKey,enc.encode(JSON.stringify(payload))));return {v:1,alg:'A256GCM',iv:b64u(iv),ct:b64u(ct)};}const d=await deviceCrypto(deviceId),iv=crypto.getRandomValues(new Uint8Array(12)),aad=commandAad(deviceId,outer.commandId,outer.type,outer.createdAt,outer.expiresAt,outer.idempotencyKey),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:iv,additionalData:enc.encode(aad)},d.key,enc.encode(JSON.stringify(payload))));return {v:2,alg:'A256GCM',kid:d.kid,iv:b64u(iv),ct:b64u(ct)};}

async function api(path,opts){opts=opts||{};const method=opts.method||'GET',body=Object.prototype.hasOwnProperty.call(opts,'body')?opts.body:null,headers={};if(body!==null)headers['Content-Type']='application/json';const res=await fetch(path,{method:method,headers:headers,body:body===null?undefined:JSON.stringify(body),cache:'no-store',credentials:'same-origin'});let data={};try{data=await res.json();}catch(e){}if(!res.ok)throw new Error(data.message||data.error||('HTTP '+res.status));return data;}
async function establishSession(){try{return await api('/api/v1/auth/check');}catch(e){}const adminToken=$('adminToken').value.trim(),totp=$('totp').value.trim();if(adminToken.length<32)throw new Error('Admin token is required for a new session.');const data=await api('/api/v1/auth/session',{method:'POST',body:{adminToken:adminToken,totp:totp}});$('adminToken').value='';$('totp').value='';return data;}
async function logoutSession(){try{await api('/api/v1/auth/logout',{method:'POST',body:{logout:true}});}catch(e){}}

function setConnected(on){$('relayDot').classList.toggle('ok',on);$('relayText').textContent=on?'Relay connected':'Not connected';}
function showUnlocked(){$('lockedPanel').hidden=true;$('appContent').hidden=false;$('lockBtn').hidden=false;$('vaultStatus').textContent='Vault unlocked in memory. Relay stores ciphertext and does not receive the Vault Key.';setConnected(true);}
function lockVault(){vaultKey=null;if(vaultRaw)vaultRaw.fill(0);vaultRaw=null;deviceKeyCache.clear();events=[];decryptedEvents=[];lastSeq=0;clearInterval(pollTimer);pollTimer=null;clearTimeout(autoLockTimer);autoLockTimer=null;clearTimeout(refreshTimer);refreshTimer=null;if(eventSource){eventSource.close();eventSource=null;}$('lockedPanel').hidden=false;$('appContent').hidden=true;$('lockBtn').hidden=true;setConnected(false);$('passphrase').value='';toast('Vault locked');}
function resetAutoLock(){lastActivity=Date.now();clearTimeout(autoLockTimer);if(vaultKey)autoLockTimer=setTimeout(()=>lockVault(),AUTO_LOCK_MS);}
['pointerdown','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>{if(vaultKey&&Date.now()-lastActivity>2000)resetAutoLock();},{passive:true}));

async function connectAndUnlock(){await establishSession();await unlockVault($('passphrase').value);showUnlocked();await fullRefresh();startRealtime();}
async function createVaultFlow(){await createVault($('passphrase').value);$('gateHint').textContent='New vault created locally. Sign in and enroll an Android node.';toast('Vault created');}

async function loadDevices(){const d=await api('/api/v1/devices');deviceKeyCache.clear();devices=d.devices||[];renderDevices();renderDeviceSelectors();}
async function loadEvents(){if(!vaultKey)return;let loops=0;while(loops++<10){const r=await api('/api/v1/events?since='+lastSeq+'&limit=500'),batch=r.events||[];if(!batch.length)break;for(const e of batch){lastSeq=Math.max(lastSeq,e.seq||0);if(events.some(x=>x.eventId===e.eventId&&x.deviceId===e.deviceId))continue;events.push(e);try{const payload=await decryptEvent(e);decryptedEvents.push(Object.assign({},e,{payload:payload}));maybeNotify(Object.assign({},e,{payload:payload}));}catch(err){decryptedEvents.push(Object.assign({},e,{payload:null,decryptError:true,decryptReason:err.message}));}}if(batch.length<500)break;}if(events.length>5000){events=events.slice(-5000);decryptedEvents=decryptedEvents.slice(-5000);}renderInbox();}
async function fullRefresh(){try{await loadDevices();await loadEvents();setConnected(true);}catch(e){setConnected(false);throw e;}}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(vaultKey)fullRefresh().catch(e=>toast(e.message));},150);}
function startRealtime(){if(eventSource)eventSource.close();if('EventSource'in window){eventSource=new EventSource('/api/v1/stream',{withCredentials:true});eventSource.addEventListener('change',scheduleRefresh);eventSource.onopen=()=>setConnected(true);eventSource.onerror=()=>setConnected(false);}clearInterval(pollTimer);pollTimer=setInterval(()=>{if(vaultKey)fullRefresh().catch(()=>{});},60000);}

function renderDeviceSelectors(){const filters=$('deviceFilter'),send=$('sendDevice'),oldF=filters.value,oldS=send.value;filters.innerHTML='<option value="">All devices</option>'+devices.map(d=>'<option value="'+escapeHtml(d.id)+'">'+escapeHtml(d.name)+'</option>').join('');send.innerHTML=devices.filter(d=>!d.revoked).map(d=>'<option value="'+escapeHtml(d.id)+'">'+escapeHtml(d.name)+'</option>').join('');if(Array.from(filters.options).some(o=>o.value===oldF))filters.value=oldF;if(Array.from(send.options).some(o=>o.value===oldS))send.value=oldS;updateSubscriptionSelector();}
function nodeChannels(d){if(!d||!d.state)return[];if(Array.isArray(d.state.channels)&&d.state.channels.length)return d.state.channels;return (d.state.subscriptions||[]).map(s=>Object.assign({id:s.channelId||String(s.subscriptionId),localId:String(s.subscriptionId),revision:s.channelRevision||1,kind:'android-sim'},s));}
function updateSubscriptionSelector(){const d=devices.find(x=>x.id===$('sendDevice').value),channels=nodeChannels(d);$('sendSubscription').innerHTML=channels.map(ch=>'<option value="'+escapeHtml(String(ch.id))+'" data-local-id="'+escapeHtml(String(ch.localId==null?'':ch.localId))+'" data-revision="'+escapeHtml(String(ch.revision||ch.channelRevision||1))+'">'+escapeHtml(ch.alias||ch.displayName||ch.carrierName||ch.id)+' · '+escapeHtml(ch.carrierName||ch.kind||'')+'</option>').join('')||'<option value="">No active SMS channel reported</option>';}
function renderDevices(){const box=$('deviceList');if(!devices.length){box.innerHTML='<div class="empty card">No enrolled devices.</div>';return;}box.innerHTML=devices.map(d=>{const s=d.state||{},subs=nodeChannels(d),buttons='<button class="ghost mini" data-action="refresh" data-id="'+escapeHtml(d.id)+'">Refresh</button><button class="ghost mini" data-action="sync" data-id="'+escapeHtml(d.id)+'">Sync history</button><button class="ghost mini" data-action="diagnostics" data-id="'+escapeHtml(d.id)+'">Diagnostics</button>'+(!d.keyId&&versionAtLeast(d.appVersion,'0.2.0')?'<button class="ghost mini" data-action="rotate-key" data-id="'+escapeHtml(d.id)+'">Isolate key</button>':'')+(d.revoked?'':'<button class="danger mini" data-action="revoke" data-id="'+escapeHtml(d.id)+'">Revoke</button>');return '<article class="card device"><div class="device-head"><div><h3>'+escapeHtml(d.name)+'</h3><p>'+escapeHtml(d.model||'Android')+' · '+escapeHtml(d.appVersion||'')+'</p></div><span class="pill '+(d.online?'online':'')+'">'+(d.revoked?'revoked':d.online?'online':'offline')+'</span></div><div class="stats"><span>Battery <strong>'+(s.batteryPct==null?'—':s.batteryPct+'%')+'</strong></span><span>Network <strong>'+escapeHtml(s.network||'—')+'</strong></span><span>Pending <strong>'+(s.pendingEvents==null?'—':s.pendingEvents)+'</strong></span></div><div class="subs">'+(subs.map(x=>'<div><strong>'+escapeHtml(x.displayName||x.carrierName||x.id||'SIM')+'</strong><small>'+escapeHtml(x.serviceState||'')+' · signal '+(x.signalLevel==null?'—':x.signalLevel)+'</small></div>').join('')||'<small>No active subscriptions reported</small>')+'</div><div class="row wrap">'+buttons+'</div></article>';}).join('');}
function collapseMessageEvents(source){
  const rank={'sms.history':0,'sms.sent':2,'sms.delivered':3,'sms.failed':4},byProvider=new Map(),rest=[];
  for(const e of source){
    const p=e.payload||{},providerId=p.providerId;
    if(p.direction==='out'&&providerId!=null){
      const key=e.deviceId+':'+providerId,old=byProvider.get(key);
      if(!old||(rank[e.kind]||0)>=(rank[old.kind]||0))byProvider.set(key,e);
    }else rest.push(e);
  }
  return rest.concat(Array.from(byProvider.values()));
}
function renderInbox(){const q=$('search').value.trim().toLowerCase(),dev=$('deviceFilter').value,kind=$('kindFilter').value,list=collapseMessageEvents(decryptedEvents).filter(e=>(!dev||e.deviceId===dev)&&(!kind||e.kind===kind)).filter(e=>{if(!q)return true;const p=e.payload||{};return [p.body,p.sender,p.recipient,p.contactName,p.otp&&p.otp.value,deviceName(e.deviceId)].some(v=>String(v||'').toLowerCase().includes(q));}).sort((a,b)=>(b.occurredAt||0)-(a.occurredAt||0));$('emptyInbox').hidden=!!list.length;let otpCount=0;$('inboxList').innerHTML=list.map(e=>{const p=e.payload||{},inbound=e.kind==='sms.received'||p.direction==='in',who=p.contactName||p.sender||p.recipient||'Unknown',body=e.decryptError?'[Unable to decrypt: '+(e.decryptReason||'vault mismatch')+']':(p.body||'');if(p.otp&&p.otp.value&&inbound)otpCount++;return '<article class="message"><div class="avatar">'+escapeHtml((who||'?').trim().slice(0,1).toUpperCase())+'</div><div><div class="msg-head"><strong>'+escapeHtml(who)+'</strong><span class="meta">'+(inbound?'received':escapeHtml(e.kind.replace('sms.','')))+' · '+escapeHtml(deviceName(e.deviceId))+'</span></div><div class="msg-body">'+escapeHtml(body)+'</div>'+(p.otp&&p.otp.value?'<div class="otp"><span>OTP</span><code>'+escapeHtml(p.otp.value)+'</code><button class="ghost mini copy-otp" data-otp="'+escapeHtml(p.otp.value)+'">Copy</button></div>':'')+'</div><div class="meta">'+fmtTime(e.occurredAt)+'<br>'+escapeHtml(p.subscriptionAlias||e.subscriptionId||'')+'</div></article>';}).join('');$('otpBadge').hidden=!otpCount;$('otpBadge').textContent=otpCount?String(otpCount):'';}

async function queueCommand(deviceId,type,payload,ttl){ttl=ttl||120;const createdAt=Math.floor(Date.now()/1000),commandId=uuid(),idempotencyKey=commandId,expiresAt=createdAt+ttl,inner=Object.assign({v:2,action:type,commandId:commandId,issuedAt:createdAt,expiresAt:expiresAt},payload),outer={commandId:commandId,idempotencyKey:idempotencyKey,type:type,createdAt:createdAt,expiresAt:expiresAt};outer.ciphertext=await encryptCommand(deviceId,outer,inner);return api('/api/v1/devices/'+encodeURIComponent(deviceId)+'/commands',{method:'POST',body:outer});}
async function sendSms(){const deviceId=$('sendDevice').value,select=$('sendSubscription'),channelId=select.value,opt=select.selectedOptions[0],to=$('sendTo').value.trim(),body=$('sendBody').value;if(!deviceId||!channelId)throw new Error('Choose an online SIM Node and SMS channel.');if(!/^\+?[0-9*# ()-]{3,40}$/.test(to))throw new Error('Recipient number format is invalid.');if(!body.trim())throw new Error('Message is empty.');const localId=opt?opt.dataset.localId:'',revision=opt?Number(opt.dataset.revision||1):1,payload={channelId:channelId,channelRevision:revision,to:to,body:body};if(/^\d+$/.test(localId))payload.subscriptionId=Number(localId);await queueCommand(deviceId,'sms.send',payload,180);$('sendBody').value='';updateCharCount();toast('Encrypted SMS command queued');}
async function createEnrollment(){if(!vaultRaw)throw new Error('Vault must be unlocked.');const name=$('enrollName').value.trim()||'Android SIM Node',nodeRaw=crypto.getRandomValues(new Uint8Array(32)),kid=await keyIdForRaw(nodeRaw),wrapped=await wrapNodeKey(nodeRaw,kid),r=await api('/api/v1/enrollments',{method:'POST',body:{ttlSeconds:600,nodeType:'android',capabilities:['sms.receive','sms.send','sms.history','signal.basic','dual-sim'],keyId:kid,wrappedKey:wrapped}}),server=location.origin,link='simhub://enroll?v=3&server='+encodeURIComponent(server)+'&token='+encodeURIComponent(r.token)+'&key='+encodeURIComponent(b64u(nodeRaw))+'&keyId='+encodeURIComponent(kid)+'&name='+encodeURIComponent(name);nodeRaw.fill(0);$('enrollLink').value=link;$('openEnroll').href=link;$('enrollResult').hidden=false;toast('Independent-key enrollment link created for 10 minutes');}
async function rotateDeviceKey(deviceId){const d=devices.find(x=>x.id===deviceId);if(!d||d.keyId)throw new Error('Device already uses an independent node key.');const raw=crypto.getRandomValues(new Uint8Array(32)),kid=await keyIdForRaw(raw),wrapped=await wrapNodeKey(raw,kid);await api('/api/v1/devices/'+encodeURIComponent(deviceId),{method:'PATCH',body:{pendingKeyId:kid,pendingWrappedKey:wrapped}});try{await queueCommand(deviceId,'node.rotate_key',{keyId:kid,nodeKey:b64u(raw)},300);}finally{raw.fill(0);}toast('Node-key rotation queued. It will activate after the device confirms the new key.');}
async function copy(text,msg){await navigator.clipboard.writeText(text);toast(msg||'Copied');}
function updateCharCount(){const value=$('sendBody').value,n=value.length,per=n>0&&/^[\x00-\x7F]*$/.test(value)?160:70;$('smsCount').textContent=n+' characters · approx. '+Math.max(1,Math.ceil(n/per))+' SMS part(s)';}
function maybeNotify(e){if(e.kind!=='sms.received'||Notification.permission!=='granted'||document.visibilityState==='visible')return;const p=e.payload||{};new Notification('SIM Hub',{body:p.otp&&p.otp.value?'New OTP received':'New SMS received',icon:'/icon.svg',tag:e.deviceId+':'+e.eventId});}
async function handleDeviceAction(btn){const id=btn.dataset.id,action=btn.dataset.action;if(action==='refresh'){await queueCommand(id,'device.refresh_state',{});toast('Refresh queued');}else if(action==='sync'){await queueCommand(id,'sms.sync_history',{maxMessages:5000},900);toast('History sync queued');}else if(action==='diagnostics'){await queueCommand(id,'diagnostics.request',{});toast('Diagnostics queued');}else if(action==='rotate-key'){await rotateDeviceKey(id);}else if(action==='revoke'&&confirm('Revoke this SIM Node? Re-enrollment will be required.')){await api('/api/v1/devices/'+encodeURIComponent(id),{method:'PATCH',body:{revoke:true}});await fullRefresh();}}
function switchView(name){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+name));$('viewTitle').textContent=titles[name][0];$('viewSubtitle').textContent=titles[name][1];if(name==='send')updateSubscriptionSelector();}

function wire(){
  $('gateHint').textContent=localStorage.getItem(VAULT_STORE)?'Local vault found. Enter its passphrase.':'No local vault found. Create or import one before enrollment.';
  $('unlockBtn').onclick=()=>connectAndUnlock().catch(e=>toast(e.message));$('createVaultBtn').onclick=()=>createVaultFlow().catch(e=>toast(e.message));$('importKeyBtn').onclick=()=>importRecoveryFlow().catch(e=>toast(e.message));$('lockBtn').onclick=lockVault;$('refreshBtn').onclick=()=>vaultKey?fullRefresh().catch(e=>toast(e.message)):toast('Vault is locked');
  document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('search').oninput=renderInbox;$('deviceFilter').onchange=renderInbox;$('kindFilter').onchange=renderInbox;$('sendDevice').onchange=updateSubscriptionSelector;$('sendBody').oninput=updateCharCount;
  $('sendBtn').onclick=()=>sendSms().catch(e=>toast(e.message));$('enrollBtn').onclick=()=>createEnrollment().catch(e=>toast(e.message));$('copyEnroll').onclick=()=>copy($('enrollLink').value,'Enrollment link copied').catch(e=>toast(e.message));$('exportKeyBtn').onclick=()=>vaultRaw?copy('SIMHUB-RECOVERY-V1:'+b64u(vaultRaw),'Recovery key copied').catch(e=>toast(e.message)):toast('Vault locked');
  $('notifyBtn').onclick=async()=>{const p=await Notification.requestPermission();toast(p==='granted'?'Browser notifications enabled':'Notification permission not granted');};
  $('forgetBtn').onclick=async()=>{if(confirm('Forget the local wrapped vault and sign this browser out?')){await logoutSession();localStorage.removeItem(VAULT_STORE);lockVault();toast('Browser credentials forgotten');}};
  $('deviceList').onclick=e=>{const b=e.target.closest('button[data-action]');if(b)handleDeviceAction(b).catch(err=>toast(err.message));};$('inboxList').onclick=e=>{const b=e.target.closest('.copy-otp');if(b)copy(b.dataset.otp,'OTP copied').catch(err=>toast(err.message));};
  if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
}
wire();
