const STORE='simhub_locale';
const dict={
'zh-CN':{
historical_sim_unverified:'历史 SIM · 归属待确认',choose_channel:'请选择发送通道',sync_recent_100:'同步最近 100 条',sync_older_100:'同步更早 100 条',mobile_fallback:'备用数据 SIM',set_sim_phone:'设置号码',phone_unknown:'号码未识别',charging_now:'充电中',not_charging:'未充电',charging_state:'充电状态',online_state:'联网状态',fallback_state:'蜂窝数据接管',not_enabled:'未启用',pending_status:'待确认',wifi_online:'已连接 Wi-Fi',cellular_online:'使用移动数据',
username:'用户名',login_passkey:'使用通行密钥登录',passkeys:'通行密钥（Passkeys）',passkeys_help:'使用 Touch ID、Windows Hello 或手机通行密钥登录。Passkey 不会解锁本地 Vault。',passkey_label:'通行密钥名称',register_passkey:'添加通行密钥',new_sms:'+ 新建短信',new_sms_hint:'输入收件人并选择 SIM 以发送加密短信。',back_messages:'返回',choose_conversation:'选择会话',choose_conversation_hint:'选择左侧短信，或点击新建短信。',

nav_inbox:'短信',nav_send:'发送短信',nav_devices:'设备',nav_settings:'设置',private_relay:'私有中继',relay_connected:'中继服务器已连接',relay_disconnected:'未连接中继服务器',lock_vault:'锁定 Vault',refresh:'刷新',
title_inbox:'短信',subtitle_inbox:'端到端加密短信',title_send:'发送短信',subtitle_send:'加密远程发送',title_devices:'设备',subtitle_devices:'SIM 节点与实时状态',title_settings:'设置',subtitle_settings:'节点注册、Vault 与通知',
connect_title:'连接你的私有中继',connect_help:'Admin Token 用于验证浏览器访问权限；Vault Key 始终只保留在本机，不会发送到 Relay。',admin_token:'Admin Token',totp:'TOTP',vault_passphrase:'Vault 密码',connect_unlock:'连接并解锁',create_vault:'创建新 Vault',session_hint:'Admin Token + TOTP 仅用于创建短期 HttpOnly 浏览器会话；根 Token 不会写入 localStorage。',
search_placeholder:'在本地搜索已解密短信…',all_devices:'全部设备',all_messages:'全部短信',received:'收到',sent:'已发送',failed:'失败',no_messages:'暂无短信。',load_older:'加载更早短信',load_newer:'加载较新短信',add_device:'添加设备',stepup_title:'确认敏感操作',stepup_cancel:'取消',stepup_confirm:'确认',sim_node:'SIM 节点',sim_subscription:'SIM / 卡槽',recipient:'收件人',message:'短信内容',recipient_placeholder:'+86…',message_placeholder:'输入短信内容',queue_sms:'发送加密短信',relay_privacy:'Relay 隐私保护',relay_privacy_help:'收件人和短信正文均在本浏览器内加密；服务器仅保存命令类型、过期时间和密文。',
enroll_node:'添加 SIM 节点',enroll_help:'创建短期一次性注册包，并为节点生成独立 Node Key。Master Vault Key 不会离开控制端。',node_type:'节点类型',android_node:'Android SIM 节点',modem_node:'Linux / DJI Modem 节点',device_label:'设备名称',device_label_placeholder:'例如：vivo SIM 节点 / DJI 4G 节点',create_enrollment:'创建注册包',copy_link:'复制注册链接',open_android:'在 Android 打开',enroll_warning:'注册完成前请把这份注册包视为密码。它只包含一次性 Enrollment Token 与 Bootstrap Secret，不包含长期 Node Key 或 Master Vault Key。',
vault:'Vault',copy_recovery:'复制恢复密钥',recovery_warning:'恢复密钥可以解密你的 SIM Hub 内容，请离线安全保存。',import_recovery:'导入恢复密钥',recovery_placeholder:'SIMHUB-RECOVERY-V1:...',import_wrap:'导入并在本浏览器加密保存',
notifications:'通知',notifications_help:'浏览器通知在 PWA 活跃时可用。后台推送可在 Relay 配置 SIMHUB_NOTIFY_BARK_URL、SIMHUB_NOTIFY_NTFY_URL 或通用 Webhook；Relay 只发送元数据。',enable_notifications:'启用浏览器通知',security:'安全',security_help:'Vault 与管理员会话空闲期限相同（默认 8 小时）；刷新自动恢复。Relay 不保存 Vault Key。',forget_credentials:'清除浏览器凭据',language:'语言',
tip_admin_token:'Relay 管理员认证令牌。仅用于建立短期浏览器会话，不会保存到 localStorage。',tip_totp:'可选的六位动态验证码。启用 Relay TOTP 后，登录时需要同时输入。',tip_vault_passphrase:'仅用于在当前浏览器解锁本地 Vault。密码和 Vault Key 不会发送到 Relay。',tip_node_type:'Android 节点使用手机 SIM；Modem 节点用于 Linux、DJI 或 USB 蜂窝 Modem。',tip_recovery:'最高敏感级别的恢复密钥，可解密 SIM Hub 内容；建议仅离线保存。',tip_notifications:'Bark、ntfy 与 Webhook 只接收新消息元数据，不接收短信正文或 OTP。',tip_security:'清除凭据会移除本浏览器保存的加密 Vault 包装数据并退出会话，不会删除服务器数据。',tip_rotate_key:'为旧节点迁移到独立 Node Key，降低单节点泄漏影响范围。',tip_revoke:'撤销后该节点无法继续同步或执行命令，需要重新注册才能恢复。',
local_vault_found:'发现本地 Vault，请输入密码。',no_local_vault:'当前浏览器没有本地 Vault，请先创建或导入。',vault_unlocked:'Vault 已在内存中解锁。Relay 仅保存密文，不会收到 Vault Key。',vault_locked:'Vault 已锁定',vault_created:'Vault 已创建',vault_created_hint:'新 Vault 已在本地创建。登录后即可添加 Android 节点。',
no_active_channel:'未报告可用短信通道',no_devices:'暂无已注册设备。',sms_ready:'短信可用',sms_unavailable:'短信不可用',sms_unverified:'短信状态未验证',sim_unavailable:'SIM 不可用',modem_unverified:'Modem 状态未验证',online:'在线',offline:'离线',revoked:'已撤销',battery:'电量',network:'网络',pending:'待处理',last_sync:'上次同步',last_sms:'上次短信',sync_error:'同步错误',none:'无',no_subscriptions:'未报告可用 SIM / 订阅',signal:'信号',
action_refresh:'刷新',action_sync:'同步历史',action_diagnostics:'诊断',action_rotate:'独立密钥',action_revoke:'撤销',unknown:'未知',decrypt_failed:'无法解密',copy:'复制',otp:'验证码',
copied:'已复制',otp_copied:'验证码已复制',enrollment_link_copied:'注册链接已复制',recovery_key_copied:'恢复密钥已复制',refresh_queued:'已加入刷新队列',history_queued:'已加入历史同步队列',diagnostics_queued:'已加入诊断队列',sms_queued:'加密短信命令已加入队列',rotation_queued:'节点密钥轮换已加入队列，设备确认后生效。',browser_notifications_enabled:'浏览器通知已启用',notification_permission_denied:'未获得通知权限',credentials_forgotten:'浏览器凭据已清除',new_otp:'收到新的验证码',new_sms:'收到新短信',
chars_parts:'{chars} 个字符 · 约 {parts} 条短信',confirm_send:'确定通过 {device} 向 {to} 发送短信？运营商可能按短信分段计费。',confirm_revoke:'确定撤销此 SIM 节点？之后需要重新注册。',confirm_forget:'确定清除本地加密 Vault 并退出此浏览器？',
err_passphrase_min:'Vault 密码至少需要 10 个字符。',err_recovery_format:'恢复密钥格式无效。',err_recovery_length:'恢复密钥长度无效。',recovery_imported:'恢复密钥已导入并在本地加密保存',err_no_vault:'当前浏览器没有 Vault，请先创建或导入。',err_bad_passphrase:'Vault 密码错误，或本地 Vault 已损坏。',err_admin_required:'建立新会话需要 Admin Token。',err_choose_node:'请选择在线 SIM 节点和短信通道。',err_recipient:'收件人号码格式无效。',err_empty_message:'短信内容为空。',err_node_sms_unavailable:'所选节点报告短信不可用，请先检查默认短信应用、权限或 SIM 状态。',err_vault_unlock:'请先解锁 Vault。',err_key_exists:'设备已经使用独立 Node Key。',err_rotation_pending:'节点密钥轮换已在进行中。',
enroll_modem_done:'一次性 Modem 注册包已创建，有效期 10 分钟',enroll_android_done:'一次性 Android 注册链接已创建，有效期 10 分钟'
},
en:{
historical_sim_unverified:'Historical SIM · unconfirmed',choose_channel:'Choose sending channel',sync_recent_100:'Sync latest 100',sync_older_100:'Sync 100 older',mobile_fallback:'Cellular failover SIM',set_sim_phone:'Set number',phone_unknown:'Number unavailable',charging_now:'Charging',not_charging:'Not charging',charging_state:'Charging',online_state:'Connection',fallback_state:'Data failover',not_enabled:'Disabled',pending_status:'Pending',wifi_online:'Wi-Fi connected',cellular_online:'Using cellular',
username:'Username',login_passkey:'Sign in with a passkey',passkeys:'Passkeys',passkeys_help:'Sign in with Touch ID, Windows Hello or a phone passkey. Passkeys do not unlock the local Vault.',passkey_label:'Passkey name',register_passkey:'Add passkey',new_sms:'+ New message',new_sms_hint:'Enter a recipient and select a SIM to send an encrypted SMS.',back_messages:'Back',choose_conversation:'Select conversation',choose_conversation_hint:'Choose a message from the list or start a new one.',

nav_inbox:'Inbox',nav_send:'Send SMS',nav_devices:'Devices',nav_settings:'Settings',private_relay:'private relay',relay_connected:'Relay connected',relay_disconnected:'Not connected',lock_vault:'Lock vault',refresh:'Refresh',
title_inbox:'Inbox',subtitle_inbox:'End-to-end encrypted SMS',title_send:'Send SMS',subtitle_send:'Encrypted remote sending',title_devices:'Devices',subtitle_devices:'SIM nodes and live state',title_settings:'Settings',subtitle_settings:'Enrollment, vault and notifications',
connect_title:'Connect your private relay',connect_help:'The Admin Token authenticates this browser to your server. The Vault Key never goes to the relay.',admin_token:'Admin Token',totp:'TOTP',vault_passphrase:'Vault passphrase',connect_unlock:'Connect & unlock',create_vault:'Create new vault',session_hint:'Admin Token + TOTP are used only to create a short-lived HttpOnly browser session; the root token is not stored in localStorage.',
search_placeholder:'Search decrypted SMS locally…',all_devices:'All devices',all_messages:'All messages',received:'Received',sent:'Sent',failed:'Failed',no_messages:'No messages yet.',load_older:'Load older messages',load_newer:'Newer messages',add_device:'Add device',stepup_title:'Confirm sensitive action',stepup_cancel:'Cancel',stepup_confirm:'Confirm',sim_node:'SIM Node',sim_subscription:'SIM / subscription',recipient:'Recipient',message:'Message',recipient_placeholder:'+86…',message_placeholder:'SMS text',queue_sms:'Queue encrypted SMS',relay_privacy:'Relay privacy',relay_privacy_help:'Recipient and SMS body are encrypted in this browser. The server stores only the command type, expiry and ciphertext.',
enroll_node:'Enroll SIM node',enroll_help:'Create a short-lived enrollment package with an independent Node Key. The Master Vault Key never leaves the controller.',node_type:'Node type',android_node:'Android SIM Node',modem_node:'Linux / DJI Modem Node',device_label:'Device label',device_label_placeholder:'e.g. vivo SIM Node / DJI 4G Node',create_enrollment:'Create enrollment package',copy_link:'Copy link',open_android:'Open on Android',enroll_warning:'Treat this enrollment package like a password until enrollment finishes. It contains only a one-time Enrollment Token and Bootstrap Secret, never the long-term Node Key or Master Vault Key.',
vault:'Vault',copy_recovery:'Copy recovery key',recovery_warning:'The recovery key can decrypt your SIM Hub content. Store it offline.',import_recovery:'Import recovery key',recovery_placeholder:'SIMHUB-RECOVERY-V1:...',import_wrap:'Import & wrap on this browser',
notifications:'Notifications',notifications_help:'Browser notifications work while this PWA is active. For background delivery configure Bark, ntfy or a generic Webhook on the relay; metadata only is sent.',enable_notifications:'Enable browser notifications',security:'Security',security_help:'Vault and administrator idle timeout match (8 hours by default), with tab refresh recovery. Relay never stores the Vault Key.',forget_credentials:'Forget browser credentials',language:'Language',
tip_admin_token:'Relay administrator authentication token. It is used only to establish a short browser session and is not stored in localStorage.',tip_totp:'Optional six-digit time-based code. It is required at login when Relay TOTP is enabled.',tip_vault_passphrase:'Used only to unlock the local Vault in this browser. The passphrase and Vault Key never go to the Relay.',tip_node_type:'Android nodes use phone SIMs; Modem nodes are for Linux, DJI or USB cellular modems.',tip_recovery:'Highest-sensitivity recovery key. It can decrypt SIM Hub content and should be stored offline.',tip_notifications:'Bark, ntfy and Webhook receive message metadata only, never SMS bodies or OTP values.',tip_security:'Forgetting credentials removes the locally wrapped Vault and signs this browser out; server data is not deleted.',tip_rotate_key:'Migrates a legacy node to an independent Node Key to reduce blast radius.',tip_revoke:'Revoking stops this node from syncing or receiving commands; re-enrollment is required.',
local_vault_found:'Local vault found. Enter its passphrase.',no_local_vault:'No local vault found. Create or import one before enrollment.',vault_unlocked:'Vault unlocked in memory. Relay stores ciphertext and does not receive the Vault Key.',vault_locked:'Vault locked',vault_created:'Vault created',vault_created_hint:'New vault created locally. Sign in and enroll an Android node.',
no_active_channel:'No active SMS channel reported',no_devices:'No enrolled devices.',sms_ready:'SMS ready',sms_unavailable:'SMS unavailable',sms_unverified:'SMS unverified',sim_unavailable:'SIM unavailable',modem_unverified:'Modem state unverified',online:'online',offline:'offline',revoked:'revoked',battery:'Battery',network:'Network',pending:'Pending',last_sync:'Last sync',last_sms:'Last SMS',sync_error:'Sync error',none:'none',no_subscriptions:'No active subscriptions reported',signal:'signal',
action_refresh:'Refresh',action_sync:'Sync history',action_diagnostics:'Diagnostics',action_rotate:'Isolate key',action_revoke:'Revoke',unknown:'Unknown',decrypt_failed:'Unable to decrypt',copy:'Copy',otp:'OTP',
copied:'Copied',otp_copied:'OTP copied',enrollment_link_copied:'Enrollment link copied',recovery_key_copied:'Recovery key copied',refresh_queued:'Refresh queued',history_queued:'History sync queued',diagnostics_queued:'Diagnostics queued',sms_queued:'Encrypted SMS command queued',rotation_queued:'Node-key rotation queued. It will activate after the device confirms the new key.',browser_notifications_enabled:'Browser notifications enabled',notification_permission_denied:'Notification permission not granted',credentials_forgotten:'Browser credentials forgotten',new_otp:'New OTP received',new_sms:'New SMS received',
chars_parts:'{chars} characters · approx. {parts} SMS part(s)',confirm_send:'Send SMS via {device} to {to}? The carrier may charge for each SMS part.',confirm_revoke:'Revoke this SIM Node? Re-enrollment will be required.',confirm_forget:'Forget the local wrapped vault and sign this browser out?',
err_passphrase_min:'Use a vault passphrase of at least 10 characters.',err_recovery_format:'Recovery key format is invalid.',err_recovery_length:'Recovery key length is invalid.',recovery_imported:'Recovery key imported and wrapped locally',err_no_vault:'No vault exists in this browser. Create or import one first.',err_bad_passphrase:'Vault passphrase is incorrect or the local vault is damaged.',err_admin_required:'Admin token is required for a new session.',err_choose_node:'Choose an online SIM Node and SMS channel.',err_recipient:'Recipient number format is invalid.',err_empty_message:'Message is empty.',err_node_sms_unavailable:'The selected node reports SMS unavailable. Fix the SMS role, permissions or SIM first.',err_vault_unlock:'Vault must be unlocked.',err_key_exists:'Device already uses an independent node key.',err_rotation_pending:'A node-key rotation is already pending.',
enroll_modem_done:'One-time modem enrollment package created for 10 minutes',enroll_android_done:'One-time Android enrollment link created for 10 minutes'
}};
export function getLocale(){const saved=localStorage.getItem(STORE);if(saved==='zh-CN'||saved==='en')return saved;return String(navigator.language||'').toLowerCase().startsWith('zh')?'zh-CN':'en';}
export function tr(key,vars={}){let text=(dict[getLocale()]||dict.en)[key]??dict.en[key]??key;for(const [k,v] of Object.entries(vars))text=text.replaceAll('{'+k+'}',String(v));return text;}
export function setLocale(locale){localStorage.setItem(STORE,locale==='en'?'en':'zh-CN');applyI18n();}
export function applyI18n(root=document){document.documentElement.lang=getLocale();root.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=tr(el.dataset.i18n);});root.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=tr(el.dataset.i18nPlaceholder);});root.querySelectorAll('[data-tip-key]').forEach(el=>{const tip=tr(el.dataset.tipKey);el.dataset.tooltip=tip;el.setAttribute('aria-label',tip);});const selector=document.getElementById('languageSelect');if(selector)selector.value=getLocale();}
const exact={'Use a vault passphrase of at least 10 characters.':'err_passphrase_min','Recovery key format is invalid.':'err_recovery_format','Recovery key length is invalid.':'err_recovery_length','Recovery key imported and wrapped locally':'recovery_imported','No vault exists in this browser. Create or import one first.':'err_no_vault','Vault passphrase is incorrect or the local vault is damaged.':'err_bad_passphrase','Admin token is required for a new session.':'err_admin_required','Vault locked':'vault_locked','Vault created':'vault_created','Choose an online SIM Node and SMS channel.':'err_choose_node','Recipient number format is invalid.':'err_recipient','Message is empty.':'err_empty_message','The selected node reports SMS unavailable. Fix the SMS role, permissions or SIM first.':'err_node_sms_unavailable','Encrypted SMS command queued':'sms_queued','Vault must be unlocked.':'err_vault_unlock','Device already uses an independent node key.':'err_key_exists','A node-key rotation is already pending.':'err_rotation_pending','Node-key rotation queued. It will activate after the device confirms the new key.':'rotation_queued','Copied':'copied','Refresh queued':'refresh_queued','History sync queued':'history_queued','Diagnostics queued':'diagnostics_queued','Enrollment link copied':'enrollment_link_copied','Recovery key copied':'recovery_key_copied','Browser notifications enabled':'browser_notifications_enabled','Notification permission not granted':'notification_permission_denied','Browser credentials forgotten':'credentials_forgotten','OTP copied':'otp_copied'};
export function localizeMessage(message){const s=String(message??'');return exact[s]?tr(exact[s]):s;}
